// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.30.0-rc1

package com.example.springredissoncodecbycache.proto;

public final class UserOuterClass {
  private UserOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "-rc1",
      UserOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.springredissoncodecbycache.proto.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id_most_sig_bits = 1;</code>
     * @return The idMostSigBits.
     */
    long getIdMostSigBits();

    /**
     * <code>int64 id_least_sig_bits = 2;</code>
     * @return The idLeastSigBits.
     */
    long getIdLeastSigBits();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string password = 5;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 5;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>bool isActive = 6;</code>
     * @return The isActive.
     */
    boolean getIsActive();

    /**
     * <code>int64 cityUuid_most_sig_bits = 7;</code>
     * @return The cityUuidMostSigBits.
     */
    long getCityUuidMostSigBits();

    /**
     * <code>int64 cityUuid_least_sig_bits = 8;</code>
     * @return The cityUuidLeastSigBits.
     */
    long getCityUuidLeastSigBits();

    /**
     * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
     * @return Whether the dateCreated field is set.
     */
    boolean hasDateCreated();
    /**
     * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
     * @return The dateCreated.
     */
    com.google.protobuf.Timestamp getDateCreated();
    /**
     * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateCreatedOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
     * @return Whether the dateUpdated field is set.
     */
    boolean hasDateUpdated();
    /**
     * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
     * @return The dateUpdated.
     */
    com.google.protobuf.Timestamp getDateUpdated();
    /**
     * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateUpdatedOrBuilder();
  }
  /**
   * Protobuf type {@code com.example.springredissoncodecbycache.proto.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.springredissoncodecbycache.proto.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "-rc1",
        User.class.getName());
    }
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      email_ = "";
      password_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.springredissoncodecbycache.proto.UserOuterClass.internal_static_com_example_springredissoncodecbycache_proto_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.springredissoncodecbycache.proto.UserOuterClass.internal_static_com_example_springredissoncodecbycache_proto_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.springredissoncodecbycache.proto.UserOuterClass.User.class, com.example.springredissoncodecbycache.proto.UserOuterClass.User.Builder.class);
    }

    private int bitField0_;
    public static final int ID_MOST_SIG_BITS_FIELD_NUMBER = 1;
    private long idMostSigBits_ = 0L;
    /**
     * <code>int64 id_most_sig_bits = 1;</code>
     * @return The idMostSigBits.
     */
    @java.lang.Override
    public long getIdMostSigBits() {
      return idMostSigBits_;
    }

    public static final int ID_LEAST_SIG_BITS_FIELD_NUMBER = 2;
    private long idLeastSigBits_ = 0L;
    /**
     * <code>int64 id_least_sig_bits = 2;</code>
     * @return The idLeastSigBits.
     */
    @java.lang.Override
    public long getIdLeastSigBits() {
      return idLeastSigBits_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object password_ = "";
    /**
     * <code>string password = 5;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 5;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISACTIVE_FIELD_NUMBER = 6;
    private boolean isActive_ = false;
    /**
     * <code>bool isActive = 6;</code>
     * @return The isActive.
     */
    @java.lang.Override
    public boolean getIsActive() {
      return isActive_;
    }

    public static final int CITYUUID_MOST_SIG_BITS_FIELD_NUMBER = 7;
    private long cityUuidMostSigBits_ = 0L;
    /**
     * <code>int64 cityUuid_most_sig_bits = 7;</code>
     * @return The cityUuidMostSigBits.
     */
    @java.lang.Override
    public long getCityUuidMostSigBits() {
      return cityUuidMostSigBits_;
    }

    public static final int CITYUUID_LEAST_SIG_BITS_FIELD_NUMBER = 8;
    private long cityUuidLeastSigBits_ = 0L;
    /**
     * <code>int64 cityUuid_least_sig_bits = 8;</code>
     * @return The cityUuidLeastSigBits.
     */
    @java.lang.Override
    public long getCityUuidLeastSigBits() {
      return cityUuidLeastSigBits_;
    }

    public static final int DATECREATED_FIELD_NUMBER = 9;
    private com.google.protobuf.Timestamp dateCreated_;
    /**
     * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
     * @return Whether the dateCreated field is set.
     */
    @java.lang.Override
    public boolean hasDateCreated() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
     * @return The dateCreated.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDateCreated() {
      return dateCreated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateCreated_;
    }
    /**
     * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDateCreatedOrBuilder() {
      return dateCreated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateCreated_;
    }

    public static final int DATEUPDATED_FIELD_NUMBER = 10;
    private com.google.protobuf.Timestamp dateUpdated_;
    /**
     * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
     * @return Whether the dateUpdated field is set.
     */
    @java.lang.Override
    public boolean hasDateUpdated() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
     * @return The dateUpdated.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDateUpdated() {
      return dateUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateUpdated_;
    }
    /**
     * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDateUpdatedOrBuilder() {
      return dateUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateUpdated_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idMostSigBits_ != 0L) {
        output.writeInt64(1, idMostSigBits_);
      }
      if (idLeastSigBits_ != 0L) {
        output.writeInt64(2, idLeastSigBits_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, email_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(password_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, password_);
      }
      if (isActive_ != false) {
        output.writeBool(6, isActive_);
      }
      if (cityUuidMostSigBits_ != 0L) {
        output.writeInt64(7, cityUuidMostSigBits_);
      }
      if (cityUuidLeastSigBits_ != 0L) {
        output.writeInt64(8, cityUuidLeastSigBits_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(9, getDateCreated());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(10, getDateUpdated());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idMostSigBits_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, idMostSigBits_);
      }
      if (idLeastSigBits_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, idLeastSigBits_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, email_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(password_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, password_);
      }
      if (isActive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isActive_);
      }
      if (cityUuidMostSigBits_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, cityUuidMostSigBits_);
      }
      if (cityUuidLeastSigBits_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, cityUuidLeastSigBits_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getDateCreated());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getDateUpdated());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.springredissoncodecbycache.proto.UserOuterClass.User)) {
        return super.equals(obj);
      }
      com.example.springredissoncodecbycache.proto.UserOuterClass.User other = (com.example.springredissoncodecbycache.proto.UserOuterClass.User) obj;

      if (getIdMostSigBits()
          != other.getIdMostSigBits()) return false;
      if (getIdLeastSigBits()
          != other.getIdLeastSigBits()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (getIsActive()
          != other.getIsActive()) return false;
      if (getCityUuidMostSigBits()
          != other.getCityUuidMostSigBits()) return false;
      if (getCityUuidLeastSigBits()
          != other.getCityUuidLeastSigBits()) return false;
      if (hasDateCreated() != other.hasDateCreated()) return false;
      if (hasDateCreated()) {
        if (!getDateCreated()
            .equals(other.getDateCreated())) return false;
      }
      if (hasDateUpdated() != other.hasDateUpdated()) return false;
      if (hasDateUpdated()) {
        if (!getDateUpdated()
            .equals(other.getDateUpdated())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_MOST_SIG_BITS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIdMostSigBits());
      hash = (37 * hash) + ID_LEAST_SIG_BITS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIdLeastSigBits());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + ISACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsActive());
      hash = (37 * hash) + CITYUUID_MOST_SIG_BITS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCityUuidMostSigBits());
      hash = (37 * hash) + CITYUUID_LEAST_SIG_BITS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCityUuidLeastSigBits());
      if (hasDateCreated()) {
        hash = (37 * hash) + DATECREATED_FIELD_NUMBER;
        hash = (53 * hash) + getDateCreated().hashCode();
      }
      if (hasDateUpdated()) {
        hash = (37 * hash) + DATEUPDATED_FIELD_NUMBER;
        hash = (53 * hash) + getDateUpdated().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.springredissoncodecbycache.proto.UserOuterClass.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.springredissoncodecbycache.proto.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.springredissoncodecbycache.proto.User)
        com.example.springredissoncodecbycache.proto.UserOuterClass.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.springredissoncodecbycache.proto.UserOuterClass.internal_static_com_example_springredissoncodecbycache_proto_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.springredissoncodecbycache.proto.UserOuterClass.internal_static_com_example_springredissoncodecbycache_proto_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.springredissoncodecbycache.proto.UserOuterClass.User.class, com.example.springredissoncodecbycache.proto.UserOuterClass.User.Builder.class);
      }

      // Construct using com.example.springredissoncodecbycache.proto.UserOuterClass.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetDateCreatedFieldBuilder();
          internalGetDateUpdatedFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        idMostSigBits_ = 0L;
        idLeastSigBits_ = 0L;
        name_ = "";
        email_ = "";
        password_ = "";
        isActive_ = false;
        cityUuidMostSigBits_ = 0L;
        cityUuidLeastSigBits_ = 0L;
        dateCreated_ = null;
        if (dateCreatedBuilder_ != null) {
          dateCreatedBuilder_.dispose();
          dateCreatedBuilder_ = null;
        }
        dateUpdated_ = null;
        if (dateUpdatedBuilder_ != null) {
          dateUpdatedBuilder_.dispose();
          dateUpdatedBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.springredissoncodecbycache.proto.UserOuterClass.internal_static_com_example_springredissoncodecbycache_proto_User_descriptor;
      }

      @java.lang.Override
      public com.example.springredissoncodecbycache.proto.UserOuterClass.User getDefaultInstanceForType() {
        return com.example.springredissoncodecbycache.proto.UserOuterClass.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.springredissoncodecbycache.proto.UserOuterClass.User build() {
        com.example.springredissoncodecbycache.proto.UserOuterClass.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.springredissoncodecbycache.proto.UserOuterClass.User buildPartial() {
        com.example.springredissoncodecbycache.proto.UserOuterClass.User result = new com.example.springredissoncodecbycache.proto.UserOuterClass.User(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.springredissoncodecbycache.proto.UserOuterClass.User result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.idMostSigBits_ = idMostSigBits_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.idLeastSigBits_ = idLeastSigBits_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.password_ = password_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.isActive_ = isActive_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.cityUuidMostSigBits_ = cityUuidMostSigBits_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.cityUuidLeastSigBits_ = cityUuidLeastSigBits_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.dateCreated_ = dateCreatedBuilder_ == null
              ? dateCreated_
              : dateCreatedBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.dateUpdated_ = dateUpdatedBuilder_ == null
              ? dateUpdated_
              : dateUpdatedBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.springredissoncodecbycache.proto.UserOuterClass.User) {
          return mergeFrom((com.example.springredissoncodecbycache.proto.UserOuterClass.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.springredissoncodecbycache.proto.UserOuterClass.User other) {
        if (other == com.example.springredissoncodecbycache.proto.UserOuterClass.User.getDefaultInstance()) return this;
        if (other.getIdMostSigBits() != 0L) {
          setIdMostSigBits(other.getIdMostSigBits());
        }
        if (other.getIdLeastSigBits() != 0L) {
          setIdLeastSigBits(other.getIdLeastSigBits());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getIsActive() != false) {
          setIsActive(other.getIsActive());
        }
        if (other.getCityUuidMostSigBits() != 0L) {
          setCityUuidMostSigBits(other.getCityUuidMostSigBits());
        }
        if (other.getCityUuidLeastSigBits() != 0L) {
          setCityUuidLeastSigBits(other.getCityUuidLeastSigBits());
        }
        if (other.hasDateCreated()) {
          mergeDateCreated(other.getDateCreated());
        }
        if (other.hasDateUpdated()) {
          mergeDateUpdated(other.getDateUpdated());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                idMostSigBits_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                idLeastSigBits_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                password_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                isActive_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                cityUuidMostSigBits_ = input.readInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                cityUuidLeastSigBits_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 74: {
                input.readMessage(
                    internalGetDateCreatedFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                input.readMessage(
                    internalGetDateUpdatedFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long idMostSigBits_ ;
      /**
       * <code>int64 id_most_sig_bits = 1;</code>
       * @return The idMostSigBits.
       */
      @java.lang.Override
      public long getIdMostSigBits() {
        return idMostSigBits_;
      }
      /**
       * <code>int64 id_most_sig_bits = 1;</code>
       * @param value The idMostSigBits to set.
       * @return This builder for chaining.
       */
      public Builder setIdMostSigBits(long value) {

        idMostSigBits_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id_most_sig_bits = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdMostSigBits() {
        bitField0_ = (bitField0_ & ~0x00000001);
        idMostSigBits_ = 0L;
        onChanged();
        return this;
      }

      private long idLeastSigBits_ ;
      /**
       * <code>int64 id_least_sig_bits = 2;</code>
       * @return The idLeastSigBits.
       */
      @java.lang.Override
      public long getIdLeastSigBits() {
        return idLeastSigBits_;
      }
      /**
       * <code>int64 id_least_sig_bits = 2;</code>
       * @param value The idLeastSigBits to set.
       * @return This builder for chaining.
       */
      public Builder setIdLeastSigBits(long value) {

        idLeastSigBits_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id_least_sig_bits = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdLeastSigBits() {
        bitField0_ = (bitField0_ & ~0x00000002);
        idLeastSigBits_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 5;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 5;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 5;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        password_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        password_ = getDefaultInstance().getPassword();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string password = 5;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        password_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private boolean isActive_ ;
      /**
       * <code>bool isActive = 6;</code>
       * @return The isActive.
       */
      @java.lang.Override
      public boolean getIsActive() {
        return isActive_;
      }
      /**
       * <code>bool isActive = 6;</code>
       * @param value The isActive to set.
       * @return This builder for chaining.
       */
      public Builder setIsActive(boolean value) {

        isActive_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>bool isActive = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsActive() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isActive_ = false;
        onChanged();
        return this;
      }

      private long cityUuidMostSigBits_ ;
      /**
       * <code>int64 cityUuid_most_sig_bits = 7;</code>
       * @return The cityUuidMostSigBits.
       */
      @java.lang.Override
      public long getCityUuidMostSigBits() {
        return cityUuidMostSigBits_;
      }
      /**
       * <code>int64 cityUuid_most_sig_bits = 7;</code>
       * @param value The cityUuidMostSigBits to set.
       * @return This builder for chaining.
       */
      public Builder setCityUuidMostSigBits(long value) {

        cityUuidMostSigBits_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int64 cityUuid_most_sig_bits = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCityUuidMostSigBits() {
        bitField0_ = (bitField0_ & ~0x00000040);
        cityUuidMostSigBits_ = 0L;
        onChanged();
        return this;
      }

      private long cityUuidLeastSigBits_ ;
      /**
       * <code>int64 cityUuid_least_sig_bits = 8;</code>
       * @return The cityUuidLeastSigBits.
       */
      @java.lang.Override
      public long getCityUuidLeastSigBits() {
        return cityUuidLeastSigBits_;
      }
      /**
       * <code>int64 cityUuid_least_sig_bits = 8;</code>
       * @param value The cityUuidLeastSigBits to set.
       * @return This builder for chaining.
       */
      public Builder setCityUuidLeastSigBits(long value) {

        cityUuidLeastSigBits_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int64 cityUuid_least_sig_bits = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCityUuidLeastSigBits() {
        bitField0_ = (bitField0_ & ~0x00000080);
        cityUuidLeastSigBits_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp dateCreated_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateCreatedBuilder_;
      /**
       * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
       * @return Whether the dateCreated field is set.
       */
      public boolean hasDateCreated() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
       * @return The dateCreated.
       */
      public com.google.protobuf.Timestamp getDateCreated() {
        if (dateCreatedBuilder_ == null) {
          return dateCreated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateCreated_;
        } else {
          return dateCreatedBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
       */
      public Builder setDateCreated(com.google.protobuf.Timestamp value) {
        if (dateCreatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateCreated_ = value;
        } else {
          dateCreatedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
       */
      public Builder setDateCreated(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateCreatedBuilder_ == null) {
          dateCreated_ = builderForValue.build();
        } else {
          dateCreatedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
       */
      public Builder mergeDateCreated(com.google.protobuf.Timestamp value) {
        if (dateCreatedBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0) &&
            dateCreated_ != null &&
            dateCreated_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getDateCreatedBuilder().mergeFrom(value);
          } else {
            dateCreated_ = value;
          }
        } else {
          dateCreatedBuilder_.mergeFrom(value);
        }
        if (dateCreated_ != null) {
          bitField0_ |= 0x00000100;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
       */
      public Builder clearDateCreated() {
        bitField0_ = (bitField0_ & ~0x00000100);
        dateCreated_ = null;
        if (dateCreatedBuilder_ != null) {
          dateCreatedBuilder_.dispose();
          dateCreatedBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateCreatedBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return internalGetDateCreatedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateCreatedOrBuilder() {
        if (dateCreatedBuilder_ != null) {
          return dateCreatedBuilder_.getMessageOrBuilder();
        } else {
          return dateCreated_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : dateCreated_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateCreated = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          internalGetDateCreatedFieldBuilder() {
        if (dateCreatedBuilder_ == null) {
          dateCreatedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDateCreated(),
                  getParentForChildren(),
                  isClean());
          dateCreated_ = null;
        }
        return dateCreatedBuilder_;
      }

      private com.google.protobuf.Timestamp dateUpdated_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateUpdatedBuilder_;
      /**
       * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
       * @return Whether the dateUpdated field is set.
       */
      public boolean hasDateUpdated() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
       * @return The dateUpdated.
       */
      public com.google.protobuf.Timestamp getDateUpdated() {
        if (dateUpdatedBuilder_ == null) {
          return dateUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateUpdated_;
        } else {
          return dateUpdatedBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
       */
      public Builder setDateUpdated(com.google.protobuf.Timestamp value) {
        if (dateUpdatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateUpdated_ = value;
        } else {
          dateUpdatedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
       */
      public Builder setDateUpdated(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateUpdatedBuilder_ == null) {
          dateUpdated_ = builderForValue.build();
        } else {
          dateUpdatedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
       */
      public Builder mergeDateUpdated(com.google.protobuf.Timestamp value) {
        if (dateUpdatedBuilder_ == null) {
          if (((bitField0_ & 0x00000200) != 0) &&
            dateUpdated_ != null &&
            dateUpdated_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getDateUpdatedBuilder().mergeFrom(value);
          } else {
            dateUpdated_ = value;
          }
        } else {
          dateUpdatedBuilder_.mergeFrom(value);
        }
        if (dateUpdated_ != null) {
          bitField0_ |= 0x00000200;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
       */
      public Builder clearDateUpdated() {
        bitField0_ = (bitField0_ & ~0x00000200);
        dateUpdated_ = null;
        if (dateUpdatedBuilder_ != null) {
          dateUpdatedBuilder_.dispose();
          dateUpdatedBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateUpdatedBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return internalGetDateUpdatedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateUpdatedOrBuilder() {
        if (dateUpdatedBuilder_ != null) {
          return dateUpdatedBuilder_.getMessageOrBuilder();
        } else {
          return dateUpdated_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : dateUpdated_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateUpdated = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          internalGetDateUpdatedFieldBuilder() {
        if (dateUpdatedBuilder_ == null) {
          dateUpdatedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDateUpdated(),
                  getParentForChildren(),
                  isClean());
          dateUpdated_ = null;
        }
        return dateUpdatedBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.example.springredissoncodecbycache.proto.User)
    }

    // @@protoc_insertion_point(class_scope:com.example.springredissoncodecbycache.proto.User)
    private static final com.example.springredissoncodecbycache.proto.UserOuterClass.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.springredissoncodecbycache.proto.UserOuterClass.User();
    }

    public static com.example.springredissoncodecbycache.proto.UserOuterClass.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.springredissoncodecbycache.proto.UserOuterClass.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_springredissoncodecbycache_proto_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_springredissoncodecbycache_proto_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022,com.example.springredisson" +
      "codecbycache.proto\032\037google/protobuf/time" +
      "stamp.proto\"\237\002\n\004User\022\030\n\020id_most_sig_bits" +
      "\030\001 \001(\003\022\031\n\021id_least_sig_bits\030\002 \001(\003\022\014\n\004nam" +
      "e\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\020\n\010password\030\005 \001(\t" +
      "\022\020\n\010isActive\030\006 \001(\010\022\036\n\026cityUuid_most_sig_" +
      "bits\030\007 \001(\003\022\037\n\027cityUuid_least_sig_bits\030\010 " +
      "\001(\003\022/\n\013dateCreated\030\t \001(\0132\032.google.protob" +
      "uf.Timestamp\022/\n\013dateUpdated\030\n \001(\0132\032.goog" +
      "le.protobuf.Timestampb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_example_springredissoncodecbycache_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_springredissoncodecbycache_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_springredissoncodecbycache_proto_User_descriptor,
        new java.lang.String[] { "IdMostSigBits", "IdLeastSigBits", "Name", "Email", "Password", "IsActive", "CityUuidMostSigBits", "CityUuidLeastSigBits", "DateCreated", "DateUpdated", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
