services:
  postgres:
    image: postgres:15.7-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cache_experiment_db
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2-alpine3.21
    ports:
      - "6380:6379"

volumes:
  postgres-data:
